name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.22"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Format
        run: gofmt -s -w . && git diff --exit-code

      - name: Tidy
        run: go mod tidy && git diff --exit-code

      - name: Lint
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2023.1.7"
          install-go: false
          cache-key: ${{ matrix.go }}

      - name: Test
        run: go test -cover -race ./...
